// Auto-generated TypeScript types from Go structs
// DO NOT EDIT - Generated by scripts/generate-types.go

export interface State {
  nodes: Node[];
  vms: VM[];
  containers: Container[];
  storage: Storage[];
  pbs: PBSInstance[];
  pbsBackups: PBSBackup[];
  metrics: Metric[];
  pveBackups: PVEBackups;
  performance: Performance;
  connectionHealth: any;
  stats: Stats;
  activeAlerts: Alert[];
  recentlyResolved: ResolvedAlert[];
  lastUpdate: string;
}

export interface Node {
  id: string;
  name: string;
  instance: string;
  status: string;
  type: string;
  cpu: number;
  memory: Memory;
  disk: Disk;
  uptime: number;
  loadAverage: number[];
  kernelVersion: string;
  pveVersion: string;
  cpuInfo: CPUInfo;
  lastSeen: string;
  connectionHealth: string;
}

export interface VM {
  id: string;
  vmid: number;
  name: string;
  node: string;
  instance: string;
  status: string;
  type: string;
  cpu: number;
  cpus: number;
  memory: Memory;
  disk: Disk;
  networkIn: number;
  networkOut: number;
  diskRead: number;
  diskWrite: number;
  uptime: number;
  template: boolean;
  lastBackup: string;
  tags: string[];
  lock: string;
  lastSeen: string;
}

export interface Container {
  id: string;
  vmid: number;
  name: string;
  node: string;
  instance: string;
  status: string;
  type: string;
  cpu: number;
  cpus: number;
  memory: Memory;
  disk: Disk;
  networkIn: number;
  networkOut: number;
  diskRead: number;
  diskWrite: number;
  uptime: number;
  template: boolean;
  lastBackup: string;
  tags: string[];
  lock: string;
  lastSeen: string;
}

export interface Storage {
  id: string;
  name: string;
  node: string;
  instance: string;
  type: string;
  status: string;
  total: number;
  used: number;
  free: number;
  usage: number;
  content: string;
  shared: boolean;
  enabled: boolean;
  active: boolean;
}

export interface PBSInstance {
  id: string;
  name: string;
  host: string;
  status: string;
  version: string;
  datastores: PBSDatastore[];
  backupJobs: PBSBackupJob[];
  syncJobs: PBSSyncJob[];
  verifyJobs: PBSVerifyJob[];
  pruneJobs: PBSPruneJob[];
  garbageJobs: PBSGarbageJob[];
  connectionHealth: string;
  lastSeen: string;
}

export interface PBSDatastore {
  name: string;
  total: number;
  used: number;
  free: number;
  usage: number;
  status: string;
  error: string;
  namespaces: PBSNamespace[];
}

export interface PBSNamespace {
  path: string;
  parent: string;
  depth: number;
}

export interface PBSBackup {
  id: string;
  instance: string;
  datastore: string;
  namespace: string;
  backupType: string;
  vmid: string;
  backupTime: string;
  size: number;
  protected: boolean;
  verified: boolean;
  comment: string;
  files: string[];
}

export interface PBSBackupJob {
  id: string;
  store: string;
  type: string;
  vmid: string;
  lastBackup: string;
  nextRun: string;
  status: string;
  error: string;
}

export interface PBSSyncJob {
  id: string;
  store: string;
  remote: string;
  status: string;
  lastSync: string;
  nextRun: string;
  error: string;
}

export interface PBSVerifyJob {
  id: string;
  store: string;
  status: string;
  lastVerify: string;
  nextRun: string;
  error: string;
}

export interface PBSPruneJob {
  id: string;
  store: string;
  status: string;
  lastPrune: string;
  nextRun: string;
  error: string;
}

export interface PBSGarbageJob {
  id: string;
  store: string;
  status: string;
  lastGarbage: string;
  nextRun: string;
  removedBytes: number;
  error: string;
}

export interface Memory {
  total: number;
  used: number;
  free: number;
  usage: number;
}

export interface Disk {
  total: number;
  used: number;
  free: number;
  usage: number;
}

export interface CPUInfo {
  model: string;
  cores: number;
  sockets: number;
  mhz: string;
}

export interface Metric {
  timestamp: string;
  type: string;
  id: string;
  values: any;
}

export interface PVEBackups {
  backupTasks: any[];
  storageBackups: any[];
  guestSnapshots: GuestSnapshot[];
}

export interface GuestSnapshot {
  id: string;
  name: string;
  node: string;
  type: string;
  vmid: number;
  time: string;
  description: string;
  parent: string;
  vmstate: boolean;
}

export interface Performance {
  apiCallDuration: any;
  lastPollDuration: number;
  pollingStartTime: string;
  totalApiCalls: number;
  failedApiCalls: number;
  cacheHits: number;
  cacheMisses: number;
}

export interface Stats {
  startTime: string;
  uptime: number;
  pollingCycles: number;
  webSocketClients: number;
  version: string;
}

// Alert types
export interface Alert {
  id: string;
  type: string;
  level: 'warning' | 'critical';
  resourceId: string;
  resourceName: string;
  node: string;
  instance: string;
  message: string;
  value: number;
  threshold: number;
  startTime: string;
  lastSeen?: string;
  acknowledged: boolean;
  ackTime?: string;
  ackUser?: string;
  metadata?: Record<string, any>;
}

export interface ResolvedAlert extends Alert {
  resolvedTime: string;
}

// WebSocket message types
export type WSMessage = 
  | { type: 'initialState'; data: State }
  | { type: 'rawData'; data: State }
  | { type: 'error'; error: string }
  | { type: 'ping'; data?: any }
  | { type: 'pong'; data?: any }
  | { type: 'welcome'; data?: any }
  | { type: 'alert'; data: Alert }
  | { type: 'alertResolved'; data: { alertId: string } };

// Utility types
export type Status = 'running' | 'stopped' | 'paused' | 'unknown';
export type GuestType = 'qemu' | 'lxc';
