// Code generated by scripts/release_control/generate_mobile_compatibility.py. DO NOT EDIT.
// Source SHA256: 85bf17ae6e6fa50233dadc7447624e1aded31b31a28339d9db1d4a0401ece107

package relay

// Notification type constants consumed by Pulse Mobile.
const (
	PushTypePatrolFinding   = "patrol_finding"
	PushTypePatrolCritical  = "patrol_critical"
	PushTypeApprovalRequest = "approval_request"
	PushTypeFixCompleted    = "fix_completed"
)

// Priority constants consumed by Pulse Mobile.
const (
	PushPriorityNormal = "normal"
	PushPriorityHigh   = "high"
)

// Action type constants consumed by Pulse Mobile.
const (
	PushActionViewFinding   = "view_finding"
	PushActionViewAlert     = "view_alert"
	PushActionApproveFix    = "approve_fix"
	PushActionDecideAction  = "decide_action"
	PushActionViewFixResult = "view_fix_result"
)
