// Code generated by scripts/release_control/generate_mobile_compatibility.py. DO NOT EDIT.
// Source SHA256: 388616526d453c26fb94fbec507042665580fdcbd637c8790a3905b05a1e1193

package relay

// Notification type constants consumed by Pulse Mobile.
const (
	PushTypePatrolFinding        = "patrol_finding"
	PushTypePatrolCritical       = "patrol_critical"
	PushTypeAlertFired           = "alert_fired"
	PushTypeExternalProbeOffline = "external_probe_offline"
	PushTypeApprovalRequest      = "approval_request"
	PushTypeFixCompleted         = "fix_completed"
)

// Priority constants consumed by Pulse Mobile.
const (
	PushPriorityNormal = "normal"
	PushPriorityHigh   = "high"
)

// Action type constants consumed by Pulse Mobile.
const (
	PushActionViewFinding   = "view_finding"
	PushActionViewAlert     = "view_alert"
	PushActionApproveFix    = "approve_fix"
	PushActionDecideAction  = "decide_action"
	PushActionViewFixResult = "view_fix_result"
)
