// Code generated by scripts/release_control/generate_mobile_compatibility.py. DO NOT EDIT.
// Source SHA256: a01ae5ea3367976f07ee8110dffb99d6c878fff8377c38b3614c5c4f6536ca1c

package relay

// Notification type constants consumed by Pulse Mobile.
const (
	PushTypePatrolFinding        = "patrol_finding"
	PushTypePatrolCritical       = "patrol_critical"
	PushTypeExternalProbeOffline = "external_probe_offline"
	PushTypeApprovalRequest      = "approval_request"
	PushTypeFixCompleted         = "fix_completed"
)

// Priority constants consumed by Pulse Mobile.
const (
	PushPriorityNormal = "normal"
	PushPriorityHigh   = "high"
)

// Action type constants consumed by Pulse Mobile.
const (
	PushActionViewFinding   = "view_finding"
	PushActionViewAlert     = "view_alert"
	PushActionApproveFix    = "approve_fix"
	PushActionDecideAction  = "decide_action"
	PushActionViewFixResult = "view_fix_result"
)
