# These are supported funding model platforms
github: rcourtman
# You can add other platforms too:
# ko_fi: # Replace with your Ko-fi username
# buy_me_a_coffee: # Replace with your Buy Me a Coffee username
# custom: ['https://example.com/donate']
