run:
  timeout: 5m
  tests: true
linters:
  disable-all: true
  enable:
    - govet
    - gofmt
    - goimports
    - errcheck
    - dupl
issues:
  max-same-issues: 0
  max-issues-per-linter: 0
  exclude-rules:
    # Exclude dupl findings in test files and mock generators — test boilerplate
    # is inherently repetitive and mock data generators share patterns by design.
    - linters: [dupl]
      path: "_test\\.go$"
    - linters: [dupl]
      path: "internal/mock/"
linters-settings:
  gofmt:
    simplify: true
  errcheck:
    exclude-functions:
      - (*encoding/json.Encoder).Encode
      - (net/http.ResponseWriter).Write
  dupl:
    threshold: 150
