{{- $secret := .Values.agent.secretEnv }}
{{- $openShiftAgent := and .Values.openShift.enabled .Values.openShift.kubernetesAgent.enabled }}
{{- if and (or .Values.agent.enabled $openShiftAgent) $secret.create (gt (len $secret.data) 0) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pulse.agentSecretName" . }}
  labels:
    {{- include "pulse.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := $secret.data }}
  {{ $key }}: {{ $value | toString | b64enc }}
  {{- end }}
{{- end }}
