// This file is generated by scripts/release_control/generate_platform_support_frontend_module.py.
// Do not edit by hand.
// Source: docs/release-control/v6/internal/PLATFORM_SUPPORT_MANIFEST.json
// Source SHA256: 8d255f43fe92759b9ea6918656d91a88c48d32e0f49729525197b6301cd7fbad

export const PLATFORM_SUPPORT_MANIFEST_SOURCE = {
  path: 'docs/release-control/v6/internal/PLATFORM_SUPPORT_MANIFEST.json',
  sha256: '8d255f43fe92759b9ea6918656d91a88c48d32e0f49729525197b6301cd7fbad',
} as const;
export const PLATFORM_SUPPORT_MANIFEST = {
  schemaVersion: 1,
  defaultInfrastructureSourceOrder: [
    'proxmox-pve',
    'agent',
    'docker',
    'proxmox-pbs',
    'proxmox-pmg',
    'kubernetes',
    'truenas',
  ],
  platforms: [
    {
      id: 'agent',
      governanceState: 'supported',
      uiLabel: 'Agent',
      uiTone: 'bg-emerald-100 text-emerald-700 dark:bg-emerald-900 dark:text-emerald-400',
      aliases: [],
      displayTokens: ['Agent'],
      storageFamily: 'onprem',
    },
    {
      id: 'docker',
      governanceState: 'supported',
      uiLabel: 'Containers',
      uiTone: 'bg-sky-100 text-sky-700 dark:bg-sky-900 dark:text-sky-400',
      aliases: [],
      displayTokens: ['Containers', 'Docker'],
      storageFamily: 'container',
    },
    {
      id: 'kubernetes',
      governanceState: 'supported',
      uiLabel: 'K8s',
      uiTone: 'bg-cyan-100 text-cyan-700 dark:bg-cyan-900 dark:text-cyan-400',
      aliases: ['k8s'],
      displayTokens: ['K8s', 'Kubernetes'],
      storageFamily: 'container',
    },
    {
      id: 'proxmox-pve',
      governanceState: 'supported',
      uiLabel: 'PVE',
      uiTone: 'bg-orange-100 text-orange-700 dark:bg-orange-900 dark:text-orange-400',
      aliases: ['pve', 'proxmox'],
      displayTokens: ['PVE', 'Proxmox VE'],
      storageFamily: 'virtualization',
    },
    {
      id: 'proxmox-pbs',
      governanceState: 'supported',
      uiLabel: 'PBS',
      uiTone: 'bg-indigo-100 text-indigo-700 dark:bg-indigo-900 dark:text-indigo-400',
      aliases: ['pbs'],
      displayTokens: ['PBS', 'Proxmox Backup Server'],
      storageFamily: 'virtualization',
    },
    {
      id: 'proxmox-pmg',
      governanceState: 'supported',
      uiLabel: 'PMG',
      uiTone: 'bg-rose-100 text-rose-700 dark:bg-rose-900 dark:text-rose-400',
      aliases: ['pmg'],
      displayTokens: ['PMG', 'Proxmox Mail Gateway'],
      storageFamily: 'virtualization',
    },
    {
      id: 'truenas',
      governanceState: 'supported',
      uiLabel: 'TrueNAS',
      uiTone: 'bg-blue-100 text-blue-700 dark:bg-blue-900 dark:text-blue-400',
      aliases: [],
      displayTokens: ['TrueNAS'],
      storageFamily: 'onprem',
    },
    {
      id: 'vmware-vsphere',
      governanceState: 'admitted',
      uiLabel: 'vSphere',
      uiTone: 'bg-blue-100 text-blue-700 dark:bg-blue-900 dark:text-blue-300',
      aliases: ['vmware'],
      displayTokens: ['vSphere', 'VMware vSphere'],
      storageFamily: 'virtualization',
    },
    {
      id: 'unraid',
      governanceState: 'presentation-only',
      uiLabel: 'Unraid',
      uiTone: 'bg-orange-100 text-orange-700 dark:bg-orange-900 dark:text-orange-300',
      aliases: [],
      displayTokens: ['Unraid'],
      storageFamily: 'onprem',
    },
    {
      id: 'synology-dsm',
      governanceState: 'presentation-only',
      uiLabel: 'Synology',
      uiTone: 'bg-emerald-100 text-emerald-700 dark:bg-emerald-900 dark:text-emerald-300',
      aliases: [],
      displayTokens: ['Synology', 'DSM'],
      storageFamily: 'onprem',
    },
    {
      id: 'microsoft-hyperv',
      governanceState: 'presentation-only',
      uiLabel: 'Hyper-V',
      uiTone: 'bg-cyan-100 text-cyan-700 dark:bg-cyan-900 dark:text-cyan-300',
      aliases: ['hyper-v'],
      displayTokens: ['Hyper-V'],
      storageFamily: 'virtualization',
    },
    {
      id: 'aws',
      governanceState: 'presentation-only',
      uiLabel: 'AWS',
      uiTone: 'bg-amber-100 text-amber-700 dark:bg-amber-900 dark:text-amber-300',
      aliases: [],
      displayTokens: ['AWS'],
      storageFamily: 'cloud',
    },
    {
      id: 'azure',
      governanceState: 'presentation-only',
      uiLabel: 'Azure',
      uiTone: 'bg-sky-100 text-sky-700 dark:bg-sky-900 dark:text-sky-300',
      aliases: [],
      displayTokens: ['Azure'],
      storageFamily: 'cloud',
    },
    {
      id: 'gcp',
      governanceState: 'presentation-only',
      uiLabel: 'GCP',
      uiTone: 'bg-red-100 text-red-700 dark:bg-red-900 dark:text-red-300',
      aliases: [],
      displayTokens: ['GCP'],
      storageFamily: 'cloud',
    },
  ],
} as const;
export const SOURCE_PLATFORM_MANIFEST_ENTRIES = PLATFORM_SUPPORT_MANIFEST.platforms;
export const SUPPORTED_PLATFORM_IDS = [
  'agent',
  'docker',
  'kubernetes',
  'proxmox-pve',
  'proxmox-pbs',
  'proxmox-pmg',
  'truenas',
] as const;
export const ADMITTED_PLATFORM_IDS = ['vmware-vsphere'] as const;
export const PRESENTATION_ONLY_PLATFORM_IDS = [
  'unraid',
  'synology-dsm',
  'microsoft-hyperv',
  'aws',
  'azure',
  'gcp',
] as const;
export const PLATFORM_TYPE_KEYS = [
  'agent',
  'docker',
  'kubernetes',
  'proxmox-pve',
  'proxmox-pbs',
  'proxmox-pmg',
  'truenas',
  'vmware-vsphere',
] as const;
export const KNOWN_SOURCE_PLATFORM_KEYS = [
  'agent',
  'docker',
  'kubernetes',
  'proxmox-pve',
  'proxmox-pbs',
  'proxmox-pmg',
  'truenas',
  'vmware-vsphere',
  'unraid',
  'synology-dsm',
  'microsoft-hyperv',
  'aws',
  'azure',
  'gcp',
  'generic',
] as const;
export const DEFAULT_INFRASTRUCTURE_SOURCE_ORDER = [
  'proxmox-pve',
  'agent',
  'docker',
  'proxmox-pbs',
  'proxmox-pmg',
  'kubernetes',
  'truenas',
] as const;
export const SOURCE_PLATFORM_ALIAS_MAP = {
  k8s: 'kubernetes',
  pve: 'proxmox-pve',
  proxmox: 'proxmox-pve',
  pbs: 'proxmox-pbs',
  pmg: 'proxmox-pmg',
  vmware: 'vmware-vsphere',
  'hyper-v': 'microsoft-hyperv',
} as const;
export const SOURCE_PLATFORM_AUDIT_TOKENS = [
  'agent',
  'docker',
  'kubernetes',
  'k8s',
  'proxmox-pve',
  'pve',
  'proxmox',
  'proxmox-pbs',
  'pbs',
  'proxmox-pmg',
  'pmg',
  'truenas',
  'vmware-vsphere',
  'vmware',
  'unraid',
  'synology-dsm',
  'microsoft-hyperv',
  'hyper-v',
  'aws',
  'azure',
  'gcp',
] as const;
export const SOURCE_PLATFORM_DISPLAY_TOKENS = [
  'Agent',
  'Containers',
  'Docker',
  'K8s',
  'Kubernetes',
  'PVE',
  'Proxmox VE',
  'PBS',
  'Proxmox Backup Server',
  'PMG',
  'Proxmox Mail Gateway',
  'TrueNAS',
  'vSphere',
  'VMware vSphere',
  'Unraid',
  'Synology',
  'DSM',
  'Hyper-V',
  'AWS',
  'Azure',
  'GCP',
] as const;
export const SOURCE_PLATFORM_PRESENTATION = {
  agent: {
    label: 'Agent',
    tone: 'bg-emerald-100 text-emerald-700 dark:bg-emerald-900 dark:text-emerald-400',
  },
  docker: {
    label: 'Containers',
    tone: 'bg-sky-100 text-sky-700 dark:bg-sky-900 dark:text-sky-400',
  },
  kubernetes: {
    label: 'K8s',
    tone: 'bg-cyan-100 text-cyan-700 dark:bg-cyan-900 dark:text-cyan-400',
  },
  'proxmox-pve': {
    label: 'PVE',
    tone: 'bg-orange-100 text-orange-700 dark:bg-orange-900 dark:text-orange-400',
  },
  'proxmox-pbs': {
    label: 'PBS',
    tone: 'bg-indigo-100 text-indigo-700 dark:bg-indigo-900 dark:text-indigo-400',
  },
  'proxmox-pmg': {
    label: 'PMG',
    tone: 'bg-rose-100 text-rose-700 dark:bg-rose-900 dark:text-rose-400',
  },
  truenas: {
    label: 'TrueNAS',
    tone: 'bg-blue-100 text-blue-700 dark:bg-blue-900 dark:text-blue-400',
  },
  'vmware-vsphere': {
    label: 'vSphere',
    tone: 'bg-blue-100 text-blue-700 dark:bg-blue-900 dark:text-blue-300',
  },
  unraid: {
    label: 'Unraid',
    tone: 'bg-orange-100 text-orange-700 dark:bg-orange-900 dark:text-orange-300',
  },
  'synology-dsm': {
    label: 'Synology',
    tone: 'bg-emerald-100 text-emerald-700 dark:bg-emerald-900 dark:text-emerald-300',
  },
  'microsoft-hyperv': {
    label: 'Hyper-V',
    tone: 'bg-cyan-100 text-cyan-700 dark:bg-cyan-900 dark:text-cyan-300',
  },
  aws: {
    label: 'AWS',
    tone: 'bg-amber-100 text-amber-700 dark:bg-amber-900 dark:text-amber-300',
  },
  azure: {
    label: 'Azure',
    tone: 'bg-sky-100 text-sky-700 dark:bg-sky-900 dark:text-sky-300',
  },
  gcp: {
    label: 'GCP',
    tone: 'bg-red-100 text-red-700 dark:bg-red-900 dark:text-red-300',
  },
  generic: {
    label: 'Generic',
    tone: 'bg-surface-alt text-base-content',
  },
} as const;
export const SOURCE_PLATFORM_STORAGE_FAMILY = {
  agent: 'onprem',
  docker: 'container',
  kubernetes: 'container',
  'proxmox-pve': 'virtualization',
  'proxmox-pbs': 'virtualization',
  'proxmox-pmg': 'virtualization',
  truenas: 'onprem',
  'vmware-vsphere': 'virtualization',
  unraid: 'onprem',
  'synology-dsm': 'onprem',
  'microsoft-hyperv': 'virtualization',
  aws: 'cloud',
  azure: 'cloud',
  gcp: 'cloud',
} as const;
export type PlatformGovernanceState =
  (typeof SOURCE_PLATFORM_MANIFEST_ENTRIES)[number]['governanceState'];
export type SourcePlatformStorageFamily =
  (typeof SOURCE_PLATFORM_MANIFEST_ENTRIES)[number]['storageFamily'];
export type GeneratedPlatformType = (typeof PLATFORM_TYPE_KEYS)[number];
export type GeneratedKnownSourcePlatform = (typeof KNOWN_SOURCE_PLATFORM_KEYS)[number];
export type GeneratedSourcePlatformManifestEntry =
  (typeof SOURCE_PLATFORM_MANIFEST_ENTRIES)[number];
