// This file is generated by scripts/generate-self-hosted-feature-catalog.go.
// Do not edit it manually.

export type SelfHostedFeatureRole =
  | 'hidden'
  | 'included'
  | 'primary_pillar'
  | 'included_extra'
  | 'compatibility_only';

export interface GeneratedSelfHostedFeatureCatalogEntry {
  key: string;
  displayName: string;
  comparisonName: string;
  showInComparisonTable: boolean;
  displayableInSelfHostedPlan: boolean;
  roles: {
    community: SelfHostedFeatureRole;
    relay: SelfHostedFeatureRole;
    pro: SelfHostedFeatureRole;
  };
  includedIn: {
    community: boolean;
    relay: boolean;
    pro: boolean;
  };
}

export const SELF_HOSTED_FEATURE_CATALOG: readonly GeneratedSelfHostedFeatureCatalogEntry[] = [
  {
    "key": "update_alerts",
    "displayName": "Update Alerts (Container/Package Updates)",
    "comparisonName": "Update Alerts",
    "showInComparisonTable": true,
    "displayableInSelfHostedPlan": true,
    "roles": {
      "community": "included",
      "relay": "included",
      "pro": "included"
    },
    "includedIn": {
      "community": true,
      "relay": true,
      "pro": true
    }
  },
  {
    "key": "sso",
    "displayName": "Basic SSO (OIDC)",
    "comparisonName": "Basic SSO (OIDC)",
    "showInComparisonTable": true,
    "displayableInSelfHostedPlan": true,
    "roles": {
      "community": "included",
      "relay": "included",
      "pro": "included"
    },
    "includedIn": {
      "community": true,
      "relay": true,
      "pro": true
    }
  },
  {
    "key": "ai_patrol",
    "displayName": "Pulse Patrol (Background Health Checks)",
    "comparisonName": "Pulse Patrol",
    "showInComparisonTable": true,
    "displayableInSelfHostedPlan": true,
    "roles": {
      "community": "included",
      "relay": "included",
      "pro": "included"
    },
    "includedIn": {
      "community": true,
      "relay": true,
      "pro": true
    }
  },
  {
    "key": "relay",
    "displayName": "Pulse Relay (Remote Access)",
    "comparisonName": "Pulse Relay (Remote Access)",
    "showInComparisonTable": true,
    "displayableInSelfHostedPlan": true,
    "roles": {
      "community": "hidden",
      "relay": "primary_pillar",
      "pro": "included"
    },
    "includedIn": {
      "community": false,
      "relay": true,
      "pro": true
    }
  },
  {
    "key": "mobile_app",
    "displayName": "Mobile App Access",
    "comparisonName": "Mobile App Access",
    "showInComparisonTable": true,
    "displayableInSelfHostedPlan": true,
    "roles": {
      "community": "hidden",
      "relay": "primary_pillar",
      "pro": "included"
    },
    "includedIn": {
      "community": false,
      "relay": true,
      "pro": true
    }
  },
  {
    "key": "push_notifications",
    "displayName": "Push Notifications",
    "comparisonName": "Push Notifications",
    "showInComparisonTable": true,
    "displayableInSelfHostedPlan": true,
    "roles": {
      "community": "hidden",
      "relay": "primary_pillar",
      "pro": "included"
    },
    "includedIn": {
      "community": false,
      "relay": true,
      "pro": true
    }
  },
  {
    "key": "ai_alerts",
    "displayName": "Alert Analysis",
    "comparisonName": "Pulse Alert Analysis",
    "showInComparisonTable": true,
    "displayableInSelfHostedPlan": true,
    "roles": {
      "community": "hidden",
      "relay": "hidden",
      "pro": "primary_pillar"
    },
    "includedIn": {
      "community": false,
      "relay": false,
      "pro": true
    }
  },
  {
    "key": "ai_autofix",
    "displayName": "Pulse Patrol Auto-Fix",
    "comparisonName": "Patrol Auto-Fix",
    "showInComparisonTable": true,
    "displayableInSelfHostedPlan": true,
    "roles": {
      "community": "hidden",
      "relay": "hidden",
      "pro": "primary_pillar"
    },
    "includedIn": {
      "community": false,
      "relay": false,
      "pro": true
    }
  },
  {
    "key": "long_term_metrics",
    "displayName": "Extended Metric History",
    "comparisonName": "Extended Metric History",
    "showInComparisonTable": false,
    "displayableInSelfHostedPlan": true,
    "roles": {
      "community": "hidden",
      "relay": "primary_pillar",
      "pro": "primary_pillar"
    },
    "includedIn": {
      "community": false,
      "relay": true,
      "pro": true
    }
  },
  {
    "key": "advanced_sso",
    "displayName": "Advanced SSO (SAML/Multi-Provider)",
    "comparisonName": "Advanced SSO (SAML/Multi-Provider)",
    "showInComparisonTable": true,
    "displayableInSelfHostedPlan": true,
    "roles": {
      "community": "hidden",
      "relay": "hidden",
      "pro": "included_extra"
    },
    "includedIn": {
      "community": false,
      "relay": false,
      "pro": true
    }
  },
  {
    "key": "rbac",
    "displayName": "Role-Based Access Control (RBAC)",
    "comparisonName": "Role-Based Access Control (RBAC)",
    "showInComparisonTable": true,
    "displayableInSelfHostedPlan": true,
    "roles": {
      "community": "hidden",
      "relay": "hidden",
      "pro": "included_extra"
    },
    "includedIn": {
      "community": false,
      "relay": false,
      "pro": true
    }
  },
  {
    "key": "audit_logging",
    "displayName": "Audit Logging",
    "comparisonName": "Audit Logging",
    "showInComparisonTable": true,
    "displayableInSelfHostedPlan": true,
    "roles": {
      "community": "hidden",
      "relay": "hidden",
      "pro": "included_extra"
    },
    "includedIn": {
      "community": false,
      "relay": false,
      "pro": true
    }
  },
  {
    "key": "advanced_reporting",
    "displayName": "PDF/CSV Reporting",
    "comparisonName": "PDF/CSV Reporting",
    "showInComparisonTable": true,
    "displayableInSelfHostedPlan": true,
    "roles": {
      "community": "hidden",
      "relay": "hidden",
      "pro": "included_extra"
    },
    "includedIn": {
      "community": false,
      "relay": false,
      "pro": true
    }
  },
  {
    "key": "agent_profiles",
    "displayName": "Centralized Agent Profiles",
    "comparisonName": "Centralized Agent Profiles",
    "showInComparisonTable": true,
    "displayableInSelfHostedPlan": true,
    "roles": {
      "community": "hidden",
      "relay": "hidden",
      "pro": "included_extra"
    },
    "includedIn": {
      "community": false,
      "relay": false,
      "pro": true
    }
  },
  {
    "key": "kubernetes_ai",
    "displayName": "Kubernetes AI Analysis (Compatibility)",
    "comparisonName": "Kubernetes AI Analysis (Compatibility)",
    "showInComparisonTable": false,
    "displayableInSelfHostedPlan": false,
    "roles": {
      "community": "hidden",
      "relay": "hidden",
      "pro": "compatibility_only"
    },
    "includedIn": {
      "community": false,
      "relay": false,
      "pro": true
    }
  },
  {
    "key": "multi_user",
    "displayName": "Multi-User Mode",
    "comparisonName": "Multi-User Mode",
    "showInComparisonTable": false,
    "displayableInSelfHostedPlan": false,
    "roles": {
      "community": "hidden",
      "relay": "hidden",
      "pro": "hidden"
    },
    "includedIn": {
      "community": false,
      "relay": false,
      "pro": false
    }
  },
  {
    "key": "white_label",
    "displayName": "White-Label Branding",
    "comparisonName": "White-Label Branding",
    "showInComparisonTable": false,
    "displayableInSelfHostedPlan": false,
    "roles": {
      "community": "hidden",
      "relay": "hidden",
      "pro": "hidden"
    },
    "includedIn": {
      "community": false,
      "relay": false,
      "pro": false
    }
  },
  {
    "key": "multi_tenant",
    "displayName": "Multi-Tenant Mode",
    "comparisonName": "Multi-Tenant Mode",
    "showInComparisonTable": false,
    "displayableInSelfHostedPlan": true,
    "roles": {
      "community": "hidden",
      "relay": "hidden",
      "pro": "hidden"
    },
    "includedIn": {
      "community": false,
      "relay": false,
      "pro": false
    }
  },
  {
    "key": "unlimited",
    "displayName": "Unlimited Instances",
    "comparisonName": "Unlimited Instances",
    "showInComparisonTable": false,
    "displayableInSelfHostedPlan": false,
    "roles": {
      "community": "hidden",
      "relay": "hidden",
      "pro": "hidden"
    },
    "includedIn": {
      "community": false,
      "relay": false,
      "pro": false
    }
  },
  {
    "key": "demo_fixtures",
    "displayName": "Demo Fixtures (Internal)",
    "comparisonName": "Demo Fixtures (Internal)",
    "showInComparisonTable": false,
    "displayableInSelfHostedPlan": false,
    "roles": {
      "community": "hidden",
      "relay": "hidden",
      "pro": "hidden"
    },
    "includedIn": {
      "community": false,
      "relay": false,
      "pro": false
    }
  }
] as const;

export const SELF_HOSTED_FEATURE_CATALOG_BY_KEY: Record<string, GeneratedSelfHostedFeatureCatalogEntry> = Object.fromEntries(
  SELF_HOSTED_FEATURE_CATALOG.map((entry) => [entry.key, entry]),
) as Record<string, GeneratedSelfHostedFeatureCatalogEntry>;

export function getSelfHostedFeatureCatalogEntry(
  key?: string | null,
): GeneratedSelfHostedFeatureCatalogEntry | null {
  const normalized = (key || '').trim();
  if (!normalized) {
    return null;
  }
  return SELF_HOSTED_FEATURE_CATALOG_BY_KEY[normalized] || null;
}

export function isDisplayableSelfHostedFeatureKey(key?: string | null): boolean {
  const entry = getSelfHostedFeatureCatalogEntry(key);
  if (!entry) {
    return true;
  }
  return entry.displayableInSelfHostedPlan;
}

export function getSelfHostedFeaturesForRole(
  tier: 'community' | 'relay' | 'pro',
  role: SelfHostedFeatureRole,
): readonly GeneratedSelfHostedFeatureCatalogEntry[] {
  return SELF_HOSTED_FEATURE_CATALOG.filter((entry) => entry.roles[tier] === role);
}
