name: Bug report
description: Create a report to help us improve (script related)
body:
  - type: markdown
    attributes:
      value: |
        **IMPORTANT:** Before submitting:
        - Please search through the closed issues to see if the bug you are reporting has already been reported and resolved. If you find a closed issue that addresses your problem, please leave a comment on that issue instead of opening a new one.
        - If you have requests for features or scripts, please share them in the Discussions section.
  - type: textarea
    id: bug
    attributes:
      label: A clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: If relevant, including screenshots or a code block can be helpful in clarifying the issue.
    validations:
      required: false
  - type: textarea
    id: expect_to_happen
    attributes:
      label: A clear and concise description of what you expected to happen.
      placeholder: I expected that ...
    validations:
      required: false
  - type: textarea
    id: reproduce
    attributes:
      label: Please provide detailed steps to reproduce the issue.
      placeholder: First do this, then this..
    validations:
      required: false
