// @vitest-environment node

import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { mkdtempSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { test } from 'vitest';
import { frozenLineStyleInputs, verifyFrozenLineStyles } from './verify-frozen-line-styles.mjs';

function fixture() {
  const root = mkdtempSync(path.join(os.tmpdir(), 'pulse-frozen-styles-'));
  mkdirSync(path.join(root, 'src/__tests__'), { recursive: true });
  mkdirSync(path.join(root, 'qualification'));
  for (const [name, content] of Object.entries({
    'index.html': '<div id="root"></div>',
    'tailwind.config.js': 'export default {}',
    'src/index.tsx': "import './final-line-styles.generated.css';",
    'src/index.css': '@tailwind utilities;',
    'src/final-line-styles.generated.css': '.hidden { display: none; }',
  }))
    writeFileSync(path.join(root, name), content);
  const snapshot = {
    version: 1,
    generated_from: { source_sha: '7d7e956077bb2d1514f7828a74923ca1f10e739f' },
    stylesheet: {
      path: 'src/final-line-styles.generated.css',
      sha256: createHash('sha256')
        .update(readFileSync(path.join(root, 'src/final-line-styles.generated.css')))
        .digest('hex'),
    },
    inputs: frozenLineStyleInputs(root),
  };
  const save = () =>
    writeFileSync(
      path.join(root, 'qualification/final-line-styles.json'),
      JSON.stringify(snapshot),
    );
  save();
  return { root, snapshot, save, cleanup: () => rmSync(root, { recursive: true, force: true }) };
}

test('accepts unchanged source and ignores test-only fixtures', () => {
  const f = fixture();
  try {
    writeFileSync(path.join(f.root, 'src/__tests__/new.test.ts'), 'const testClass = "p-2";');
    assert.equal(verifyFrozenLineStyles(f.root).stylesheet.sha256, f.snapshot.stylesheet.sha256);
  } finally {
    f.cleanup();
  }
});

for (const name of ['src/index.css', 'src/index.tsx', 'tailwind.config.js', 'index.html']) {
  test(`rejects changed ${name} before a build`, () => {
    const f = fixture();
    try {
      writeFileSync(path.join(f.root, name), 'changed');
      assert.throws(() => verifyFrozenLineStyles(f.root), /style inputs changed/);
    } finally {
      f.cleanup();
    }
  });
}

test('rejects a new runtime caller, even when every old hash matches', () => {
  const f = fixture();
  try {
    writeFileSync(path.join(f.root, 'src/new.tsx'), '<div class="new-class" />');
    assert.throws(() => verifyFrozenLineStyles(f.root), /style inputs changed/);
  } finally {
    f.cleanup();
  }
});

test('rejects changed generated bytes', () => {
  const f = fixture();
  try {
    writeFileSync(
      path.join(f.root, 'src/final-line-styles.generated.css'),
      '.hidden { display: block; }',
    );
    assert.throws(() => verifyFrozenLineStyles(f.root), /stylesheet changed/);
  } finally {
    f.cleanup();
  }
});

test('rejects an output path that would bypass the fixed stylesheet binding', () => {
  const f = fixture();
  try {
    f.snapshot.stylesheet.path = 'src/index.css';
    f.save();
    assert.throws(() => verifyFrozenLineStyles(f.root), /Invalid frozen line/);
  } finally {
    f.cleanup();
  }
});

test('the real Vite and embed paths both verify the snapshot', () => {
  const root = path.resolve(import.meta.dirname, '..');
  for (const name of ['vite.config.ts', 'scripts/build-embed-assets.mjs']) {
    assert.match(readFileSync(path.join(root, name), 'utf8'), /verifyFrozenLineStyles\(\)/);
  }
});
