package vmware

import "time"

func DefaultFixtures() InventorySnapshot {
	collectedAt := time.Date(2026, time.March, 31, 9, 45, 0, 0, time.UTC)

	accessible := true
	multipleHostAccess := true

	return InventorySnapshot{
		ConnectionID:   "vc-mock-1",
		ConnectionName: "Lab vCenter",
		VCenterHost:    "vcsa.lab.local",
		VIRelease:      "8.0.3",
		CollectedAt:    collectedAt,
		Hosts: []InventoryHost{
			{
				Host:                "host-101",
				Name:                "esxi-01.lab.local",
				ConnectionState:     "CONNECTED",
				PowerState:          "POWERED_ON",
				HostUUID:            "uuid-host-101",
				DatacenterID:        "datacenter-1",
				DatacenterName:      "Primary DC",
				ComputeResourceID:   "domain-c101",
				ComputeResourceName: "Production Cluster",
				ClusterID:           "domain-c101",
				ClusterName:         "Production Cluster",
				FolderID:            "group-h4",
				FolderName:          "Cluster Hosts",
				DatastoreIDs:        []string{"datastore-201", "datastore-202"},
				DatastoreNames:      []string{"nvme-primary", "archive-tier"},
				OverallStatus:       "green",
				Metrics: &InventoryMetrics{
					CPUPercent:              float64Ptr(27.4),
					MemoryPercent:           float64Ptr(58.1),
					MemoryUsedBytes:         int64Ptr(49_902_682_112),
					MemoryTotalBytes:        int64Ptr(85_899_345_920),
					NetInBytesPerSecond:     float64Ptr(1_240_000),
					NetOutBytesPerSecond:    float64Ptr(980_000),
					DiskReadBytesPerSecond:  float64Ptr(2_280_000),
					DiskWriteBytesPerSecond: float64Ptr(1_920_000),
				},
				RecentTasks: []InventoryTask{{
					Task:      "task-301",
					Name:      "Apply host profile remediation",
					State:     "success",
					StartedAt: collectedAt.Add(-28 * time.Minute),
				}},
			},
			{
				Host:                "host-102",
				Name:                "esxi-02.lab.local",
				ConnectionState:     "CONNECTED",
				PowerState:          "POWERED_ON",
				HostUUID:            "uuid-host-102",
				DatacenterID:        "datacenter-1",
				DatacenterName:      "Primary DC",
				ComputeResourceID:   "domain-c101",
				ComputeResourceName: "Production Cluster",
				ClusterID:           "domain-c101",
				ClusterName:         "Production Cluster",
				FolderID:            "group-h4",
				FolderName:          "Cluster Hosts",
				DatastoreIDs:        []string{"datastore-201"},
				DatastoreNames:      []string{"nvme-primary"},
				OverallStatus:       "yellow",
				Metrics: &InventoryMetrics{
					CPUPercent:              float64Ptr(43.6),
					MemoryPercent:           float64Ptr(71.5),
					MemoryUsedBytes:         int64Ptr(61_419_929_600),
					MemoryTotalBytes:        int64Ptr(85_899_345_920),
					NetInBytesPerSecond:     float64Ptr(1_960_000),
					NetOutBytesPerSecond:    float64Ptr(1_420_000),
					DiskReadBytesPerSecond:  float64Ptr(3_180_000),
					DiskWriteBytesPerSecond: float64Ptr(2_540_000),
				},
				TriggeredAlarms: []InventoryAlarm{{
					Alarm:         "alarm-401",
					Name:          "Host memory contention",
					OverallStatus: "yellow",
					TriggeredAt:   collectedAt.Add(-11 * time.Minute),
				}},
				RecentTasks: []InventoryTask{{
					Task:      "task-302",
					Name:      "vMotion virtual machine",
					State:     "running",
					StartedAt: collectedAt.Add(-3 * time.Minute),
				}},
			},
		},
		VMs: []InventoryVM{
			{
				VM:                  "vm-201",
				Name:                "orders-api-01",
				PowerState:          "POWERED_ON",
				CPUCount:            4,
				MemorySizeMiB:       16 * 1024,
				DatacenterID:        "datacenter-1",
				DatacenterName:      "Primary DC",
				ComputeResourceID:   "domain-c101",
				ComputeResourceName: "Production Cluster",
				ClusterID:           "domain-c101",
				ClusterName:         "Production Cluster",
				FolderID:            "group-v7",
				FolderName:          "Production VMs",
				ResourcePoolID:      "resgroup-22",
				ResourcePoolName:    "Tier 1",
				RuntimeHostID:       "host-101",
				RuntimeHostName:     "esxi-01.lab.local",
				DatastoreIDs:        []string{"datastore-201"},
				DatastoreNames:      []string{"nvme-primary"},
				InstanceUUID:        "vm-instance-201",
				BIOSUUID:            "vm-bios-201",
				GuestOSFamily:       "LINUX",
				GuestHostname:       "orders-api-01.internal",
				GuestIPAddresses:    []string{"10.42.10.21"},
				OverallStatus:       "green",
				SnapshotCount:       1,
				Metrics: &InventoryMetrics{
					CPUPercent:              float64Ptr(36.2),
					MemoryPercent:           float64Ptr(64.4),
					MemoryUsedBytes:         int64Ptr(11_058_069_504),
					MemoryTotalBytes:        int64Ptr(17_179_869_184),
					NetInBytesPerSecond:     float64Ptr(620_000),
					NetOutBytesPerSecond:    float64Ptr(710_000),
					DiskReadBytesPerSecond:  float64Ptr(1_180_000),
					DiskWriteBytesPerSecond: float64Ptr(940_000),
				},
				RecentEvents: []InventoryEvent{{
					Event:     "event-501",
					Type:      "VmMessageEvent",
					Message:   "Snapshot completed successfully",
					User:      "svc-pulse",
					CreatedAt: collectedAt.Add(-46 * time.Minute),
				}},
			},
			{
				VM:                  "vm-202",
				Name:                "postgres-ha-01",
				PowerState:          "POWERED_ON",
				CPUCount:            8,
				MemorySizeMiB:       32 * 1024,
				DatacenterID:        "datacenter-1",
				DatacenterName:      "Primary DC",
				ComputeResourceID:   "domain-c101",
				ComputeResourceName: "Production Cluster",
				ClusterID:           "domain-c101",
				ClusterName:         "Production Cluster",
				FolderID:            "group-v7",
				FolderName:          "Production VMs",
				ResourcePoolID:      "resgroup-23",
				ResourcePoolName:    "Stateful",
				RuntimeHostID:       "host-102",
				RuntimeHostName:     "esxi-02.lab.local",
				DatastoreIDs:        []string{"datastore-201", "datastore-202"},
				DatastoreNames:      []string{"nvme-primary", "archive-tier"},
				InstanceUUID:        "vm-instance-202",
				BIOSUUID:            "vm-bios-202",
				GuestOSFamily:       "LINUX",
				GuestHostname:       "postgres-ha-01.internal",
				GuestIPAddresses:    []string{"10.42.10.32"},
				OverallStatus:       "yellow",
				SnapshotCount:       3,
				Metrics: &InventoryMetrics{
					CPUPercent:              float64Ptr(58.8),
					MemoryPercent:           float64Ptr(82.1),
					MemoryUsedBytes:         int64Ptr(28_215_830_528),
					MemoryTotalBytes:        int64Ptr(34_359_738_368),
					NetInBytesPerSecond:     float64Ptr(880_000),
					NetOutBytesPerSecond:    float64Ptr(930_000),
					DiskReadBytesPerSecond:  float64Ptr(2_940_000),
					DiskWriteBytesPerSecond: float64Ptr(3_220_000),
				},
				TriggeredAlarms: []InventoryAlarm{{
					Alarm:         "alarm-402",
					Name:          "Virtual machine memory usage",
					OverallStatus: "yellow",
					TriggeredAt:   collectedAt.Add(-17 * time.Minute),
				}},
				RecentTasks: []InventoryTask{{
					Task:      "task-303",
					Name:      "Consolidate virtual machine disks",
					State:     "queued",
					StartedAt: collectedAt.Add(-2 * time.Minute),
				}},
			},
			{
				VM:                  "vm-203",
				Name:                "batch-worker-01",
				PowerState:          "POWERED_OFF",
				CPUCount:            4,
				MemorySizeMiB:       8 * 1024,
				DatacenterID:        "datacenter-1",
				DatacenterName:      "Primary DC",
				ComputeResourceID:   "domain-c101",
				ComputeResourceName: "Production Cluster",
				ClusterID:           "domain-c101",
				ClusterName:         "Production Cluster",
				FolderID:            "group-v8",
				FolderName:          "Batch VMs",
				ResourcePoolID:      "resgroup-24",
				ResourcePoolName:    "Workers",
				RuntimeHostID:       "host-101",
				RuntimeHostName:     "esxi-01.lab.local",
				DatastoreIDs:        []string{"datastore-202"},
				DatastoreNames:      []string{"archive-tier"},
				InstanceUUID:        "vm-instance-203",
				BIOSUUID:            "vm-bios-203",
				GuestOSFamily:       "LINUX",
				GuestHostname:       "batch-worker-01.internal",
				GuestIPAddresses:    []string{},
				OverallStatus:       "gray",
			},
		},
		Datastores: []InventoryDatastore{
			{
				Datastore:          "datastore-201",
				Name:               "nvme-primary",
				Type:               "VMFS",
				FreeSpace:          3_800_000_000_000,
				Capacity:           8_000_000_000_000,
				DatacenterID:       "datacenter-1",
				DatacenterName:     "Primary DC",
				FolderID:           "group-s4",
				FolderName:         "Datastores",
				HostIDs:            []string{"host-101", "host-102"},
				HostNames:          []string{"esxi-01.lab.local", "esxi-02.lab.local"},
				VMIDs:              []string{"vm-201", "vm-202"},
				VMNames:            []string{"orders-api-01", "postgres-ha-01"},
				Accessible:         &accessible,
				MultipleHostAccess: &multipleHostAccess,
				MaintenanceMode:    "normal",
				URL:                "ds:///vmfs/volumes/datastore-201/",
				OverallStatus:      "green",
			},
			{
				Datastore:          "datastore-202",
				Name:               "archive-tier",
				Type:               "NFS41",
				FreeSpace:          11_000_000_000_000,
				Capacity:           16_000_000_000_000,
				DatacenterID:       "datacenter-1",
				DatacenterName:     "Primary DC",
				FolderID:           "group-s4",
				FolderName:         "Datastores",
				HostIDs:            []string{"host-101"},
				HostNames:          []string{"esxi-01.lab.local"},
				VMIDs:              []string{"vm-202", "vm-203"},
				VMNames:            []string{"postgres-ha-01", "batch-worker-01"},
				Accessible:         &accessible,
				MultipleHostAccess: &multipleHostAccess,
				MaintenanceMode:    "normal",
				URL:                "ds:///nfs/archive-tier/",
				OverallStatus:      "yellow",
				RecentTasks: []InventoryTask{{
					Task:      "task-304",
					Name:      "Rescan datastore",
					State:     "success",
					StartedAt: collectedAt.Add(-14 * time.Minute),
				}},
			},
		},
	}
}
