name: Update .app-headers in /misc

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  update-and-merge-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.CREATE_HEADER_APP_ID }}  
          private-key: ${{ secrets.CREATE_HEADER_SECRET }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Figlet
        run: sudo apt-get install -y figlet

      - name: Run generate-app-headers script
        run: |
          bash .github/workflows/generate-app-headers.sh

      - name: Create or update branch
        run: |
          # Check if the branch exists, create it if it doesn't exist
          git fetch origin
          if ! git show-ref --quiet refs/heads/update-app-headers; then
            git checkout -b update-app-headers
          else
            git checkout update-app-headers
          fi
          
          # Configure Git user info
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Check if the file exists, and if not, create it
          if [ ! -f "./misc/.app-headers" ]; then
            echo "File .app-headers not found, creating it."
            touch ./misc/.app-headers
          fi
          
          # Make sure there are changes to commit (whether new or modified file)
          git diff --quiet || git commit -am "[core]: update .app-headers to latest version"
          
          # Push changes to the branch if there are any
          git push origin update-app-headers --force || echo "No changes to push"

      - name: Check if there are changes before creating PR
        id: check-changes
        run: |
          # Check if there are any changes between 'main' and 'update-app-headers'
          git fetch origin
          git diff --quiet origin/main..update-app-headers
          if [ $? -eq 0 ]; then
            echo "No changes detected, skipping PR creation."
            echo "skip_pr_creation=true" >> $GITHUB_ENV
          else
            echo "Changes detected, proceeding with PR creation."
          fi

      - name: Create pull request
        id: create-pr
        if: env.skip_pr_creation != 'true'  # Only create PR if changes are detected
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_EXISTS=$(gh pr list --head "update-app-headers" --json number --jq '.[].number')
          if [ -z "$PR_EXISTS" ]; then
            # Create the pull request if it doesn't exist
            gh pr create --title "[core]: update .app-headers to latest version" \
                         --body "This PR automatically updates the app-headers file." \
                         --head update-app-headers \
                         --base main
          else
            echo "PR already exists, skipping creation."
          fi

      - name: Final Status
        run: |
          echo "Workflow completed successfully."
