name: Create new release

on:
  schedule:
    # Runs "At 00:01 every night" (UTC)
    - cron: '1 0 * * *'
  workflow_dispatch:  # Allows manual execution

jobs:
  create-new-release:
    runs-on: runner-cluster-htl-set
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Parse CHANGELOG.md for yesterday's entries and create a new release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          YESTERDAY=$(date -u --date="yesterday" +%Y-%m-%d)
          awk '/^## '"$YESTERDAY"'/ {f=1; next} f && /^## [0-9]{4}-[0-9]{2}-[0-9]{2}/ {f=0} f && !/^## / {print}' CHANGELOG.md > changelog_tmp.md

          if [ ! -s changelog_tmp.md ]; then
            echo "No changes found for $YESTERDAY, skipping release."
            exit 0
          fi

          CHANGELOG_SIZE=$(wc -c < changelog_tmp.md)

          if [ "$CHANGELOG_SIZE" -gt 10000 ]; then
            echo "ERROR: Changelog is too large to process automatically! Manual review required."
            echo "To manually trigger the release, use the 'workflow_dispatch' event."
            exit 1
          fi

          # Creating the GitHub release (without --latest)
          gh release create "$YESTERDAY" -t "$YESTERDAY" -F changelog_tmp.md
