name: Create new release

on:
  schedule:
    - cron: '1 0 * * *'  # Runs nightly
  workflow_dispatch:

jobs:
  create-new-release:
    runs-on: runner-cluster-htl-set
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Parse CHANGELOG.md for yesterday's entries and create a new release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          YESTERDAY=$(date -u --date="yesterday" +%Y-%m-%d)

          # Extract entries for only yesterday
          awk -v date="## $YESTERDAY" '
            $0 ~ date {found=1; next} 
            found && /^## [0-9]{4}-[0-9]{2}-[0-9]{2}/ {found=0} 
            found {print}
          ' CHANGELOG.md > changelog_tmp.md

          if [ ! -s changelog_tmp.md ]; then
            echo "No changes found for $YESTERDAY, skipping release."
            exit 0
          fi

          CHANGELOG_SIZE=$(wc -c < changelog_tmp.md)
          echo "Changelog size: $CHANGELOG_SIZE bytes"

          if [ "$CHANGELOG_SIZE" -gt 10000 ]; then
            echo "WARNING: Changelog too large, cropping to last 10,000 bytes..."
            tail -c 10000 changelog_tmp.md > changelog_cropped.md
            mv changelog_cropped.md changelog_tmp.md
          fi

          echo "Creating GitHub release for $YESTERDAY..."
          gh release create "$YESTERDAY" -t "$YESTERDAY" -F changelog_tmp.md
