name: Create new release

on:
  schedule:
    - cron: '1 0 * * *'  # Runs nightly
  workflow_dispatch:
    inputs:
      force_release:
        description: "Bypass changelog size limit"
        required: false
        default: "false"

jobs:
  create-new-release:
    runs-on: runner-cluster-htl-set
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Parse CHANGELOG.md for yesterday's entries and create a new release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FORCE_RELEASE: ${{ github.event.inputs.force_release }}
        run: |
          YESTERDAY=$(date -u --date="yesterday" +%Y-%m-%d)
          awk '/^## '"$YESTERDAY"'/ {f=1; next} f && /^## [0-9]{4}-[0-9]{2}-[0-9]{2}/ {f=0} f && !/^## / {print}' CHANGELOG.md > changelog_tmp.md

          if [ ! -s changelog_tmp.md ]; then
            echo "No changes found for $YESTERDAY, skipping release."
            exit 0
          fi

          CHANGELOG_SIZE=$(wc -c < changelog_tmp.md)
          echo "Changelog size: $CHANGELOG_SIZE bytes"

          if [ "$CHANGELOG_SIZE" -gt 10000 ] && [ "$FORCE_RELEASE" != "true" ]; then
            echo "ERROR: Changelog is too large! Manual review required."
            echo "To manually trigger the release, use 'workflow_dispatch' with 'force_release: true'."
            exit 1
          fi

          echo "Creating GitHub release for $YESTERDAY..."
          gh release create "$YESTERDAY" -t "$YESTERDAY" -F changelog_tmp.md
