name: Update JSON Date in PR

on:
  pull_request:
    paths:
      - '.github/workflows/scripts/*.sh'
      - 'json/*.json'
    types: [opened, synchronize, reopened]

  schedule:
    - cron: '0 */2 * * *' 

jobs:
  update_json:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Make script executable
        run: chmod +x .github/workflows/scripts/update_json_date.sh

      - name: Run the update script
        run: ./.github/workflows/scripts/update_json_date.sh
