name: Auto Update JSON-Dates

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-json-dates:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 10  # Fetch at least 2 commits to compare changes

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Find newly created JSON files from today
        id: find_new_json
        run: |
          TODAY=$(date -u +"%Y-%m-%d")

          git fetch origin main --depth=1

          NEW_JSON_FILES=$(git log --since="$TODAY 00:00:00" --diff-filter=A --name-only --pretty=format: origin/main -- json/*.json || true)

          if [[ -z "$NEW_JSON_FILES" ]]; then
            echo "No new JSON files created today."
            echo "CHANGED=false" >> $GITHUB_ENV
          else
            echo "New JSON files detected today:"
            echo "$NEW_JSON_FILES"
            echo "$NEW_JSON_FILES" > new_json_files.txt
            echo "CHANGED=true" >> $GITHUB_ENV
          fi

      - name: Run update script
        if: env.CHANGED == 'true'
        run: |
          chmod +x .github/workflows/scripts/update-json.sh
          while read -r FILE; do
            .github/workflows/scripts/update-json.sh "$FILE"
          done < new_json_files.txt

      - name: Commit and create PR if changes exist
        if: env.CHANGED == 'true'
        run: |
          git add json/*.json
          git commit -m "Auto-update date_created in new JSON files"
          git checkout -b pr-update-json-dates
          git push origin pr-update-json-dates --force
          gh pr create --title "[core] Auto-update new JSON files" \
                       --body "This PR is auto-generated to update the `date_created` field in newly created JSON files." \
                       --head pr-update-json-dates \
                       --base main \
                       --label "automated pr"
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}

      - name: Approve pull request
        if: env.CHANGED == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=$(gh pr list --head "pr-update-json-dates" --json number --jq '.[].number')
          if [ -n "$PR_NUMBER" ]; then
            gh pr review $PR_NUMBER --approve
          fi
